<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>Project Atomic  &raquo; Blog Archive   &raquo; jQuery Flickr</title>

<link rel="stylesheet" href="http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic/css/reset.css" type="text/css" media="screen" />
<link rel="stylesheet" href="http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic/style.css" type="text/css" media="screen" />
<!--[if lt IE 7]><link rel="stylesheet" href="http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic/css/ie.css" type="text/css" media="screen" /><![endif]-->
<link rel="alternate" type="application/rss+xml" title="Project Atomic RSS Feed" href="http://www.projectatomic.com/feed/" />
<link rel="pingback" href="http://www.projectatomic.com/wordpress/xmlrpc.php" />
<script type="text/javascript">var PA_PATH = "http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic";</script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.projectatomic.com/wordpress/xmlrpc.php?rsd" />

<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.projectatomic.com/wordpress/wp-includes/wlwmanifest.xml" /> 
<script type='text/javascript' src='http://www.projectatomic.com/wordpress/wp-includes/js/jquery/jquery.js?ver=1.2.6'></script>
<script type='text/javascript' src='http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic/js/script.js?ver=2.6'></script>
<meta name="generator" content="WordPress 2.6" />


<!-- Start Of Script Generated By cforms v8.6.1 [Oliver Seidel | www.deliciousdays.com] -->
<link rel="stylesheet" type="text/css" href="http://www.projectatomic.com/wordpress/wp-content/plugins/cforms/styling/minimal.css" />
<script type="text/javascript" src="http://www.projectatomic.com/wordpress/wp-content/plugins/cforms/js/cforms.js"></script>
<!-- End Of Script Generated By cforms -->

<script src="http://www.projectatomic.com/wordpress/wp-content/uploads/code/jquery.flickr-1.0-min.js" type="text/javascript"></script>  <script type="text/javascript"> 
	jQuery(function(){   
		jQuery("#gallery-flickr").flickr({     
			api_key: "f28804be7a09c5845676349c7e47d636",     
			per_page: 14   
		}); 
		jQuery("#btnRefresh").click(function(){
			jQuery("#gallery").html("").flickr({     
				api_key: "f28804be7a09c5845676349c7e47d636",     
				per_page: 14   
			});
		}); 
	}); 

</script>

<link rel="stylesheet" href="http://www.projectatomic.com/wordpress/wp-content/plugins/wp-syntax/wp-syntax.css" type="text/css" media="screen" />

</head>
<body>
<div id="page">

<div id="header" class="secondary">
	<div class="wrapper">
		<h1><a href="http://www.projectatomic.com/"><img src="http://www.projectatomic.com/wordpress/wp-content/themes/projectatomic/images/logo.png" alt="Logo" /></a></h1>
		<!--<h1><a href="http://www.projectatomic.com/">Project Atomic</a></h1>-->
    <h2>WEB DEVELOPMENT 2.0</h2>

		<ul id="loginout">
		  <li><a href="http://www.projectatomic.com/wordpress/wp-login.php?action=register">Register</a></li>      <li><a href="http://www.projectatomic.com/wordpress/wp-login.php">Log in</a></li>
    </ul>

    <ul id="headermenu" class="clear">
      <li class="page_item page-item-6"><a href="http://www.projectatomic.com/project/" title="Projects">Projects</a></li>
<li class="page_item page-item-131"><a href="http://www.projectatomic.com/websites/" title="Websites">Websites</a></li>

<li class="page_item page-item-182"><a href="http://www.projectatomic.com/contact/" title="Contact">Contact</a></li>
<li class="page_item page-item-2"><a href="http://www.projectatomic.com/about/" title="About">About</a></li>
    </ul>
	</div><!-- .wrapper -->
</div><!-- #header -->
<div class="wrapper">
	<div id="content">
<h4>Demo</h4>
<p id="gallery-flickr" class="gallery">&nbsp;</p>

  </div><!-- .wrapper -->
</div><!-- #footer -->
</div><!-- #page -->
</body>
</html>
